modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="suggestionproviderfix"
version="${file.jarVersion}"
displayName="Suggestion Provider Fix"
updateJSONURL="https://github.com/Harleyoc1/SuggestionProviderFix/blob/1.16.5/version_info.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/suggestion-provider-fix"
credits=""
authors="Harley O'Connor"
description='''
Simple fix to the suggestion provider which autocompletes modded namespaces properly.
'''

[[dependencies.suggestionproviderfix]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.suggestionproviderfix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
